

export const COMPANY_INFO = {
    name: "Vaizans Group",
    tagline: "Investment & Growth Partners",
    description:
        "Professional business group with 13+ members, 7 successful projects, and  profitable returns. Specializing in farming, retail, and property investments.",
    email: "vaizansgroup@gmail.com",
    phone: "",
    whatsapp: "",
    location: "Mirpur 11, Dhaka, Bangladesh",
    founded: "2022",
}

export const NAVIGATION_ITEMS = [
    { name: "Home", href: "/" },
    { name: "About", href: "/about" },
    { name: "Team", href: "/team" },
    {
        name: "Projects",
        href: "/projects",
        dropdown: [
            { name: "All Projects", href: "/projects" },
            { name: "Farming Projects", href: "/projects/farming" },
            { name: "Retail Projects", href: "/projects/retail" },
            { name: "Livestock Projects", href: "/projects/livestock" },
        ],
    },
    { name: "Investments", href: "/investments" },
    { name: "Gallery", href: "/gallery" },
    { name: "News", href: "/news" },
    { name: "Contact", href: "/contact" },
]

export const STATS_DATA = [
    {
        value: "13+",
        label: "Active Members",
        description: "Group A (10) + Group B (3)",
        icon: "Users",
        trend: "+3 this year",
    },
    {
        value: "7",
        label: "Completed Projects",
        description: "All Profitable Ventures",
        icon: "Target",
        trend: "70% Success",
    },
    {
        value: "70%",
        label: "Success Rate",
        description: "Profitable Returns",
        icon: "TrendingUp",
        trend: "Consistent Growth",
    },
    {
        value: "4+",
        label: "Investment Sectors",
        description: "Diversified Portfolio",
        icon: "Building",
        trend: "Expanding",
    },
]

export const PROJECTS_DATA = [
    {
        id: 1,
        title: "Pond Fishing Venture",
        category: "Aquaculture",
        year: "2022",
        duration: "4 months",
        status: "Completed",
        profit: "Good",
        profitPercent: "15%",
        investment: "৳1L",
        returns: "৳1.5L",
        location: "Feni",
        members: 8,
        image: "/image/Pond-Fishing-Venture.jpg",
        description:
            "Large-scale fish farming operation with modern pond management techniques and sustainable practices.",

    },
    {
        id: 2,
        title: "Hen Farming Operation",
        category: "Poultry",
        year: "2023",
        duration: "6 months",
        status: "Completed",
        profit: "Good",
        profitPercent: "10%",
        investment: "৳1L",
        returns: "৳1.1L",
        location: "Feni",
        members: 10,
        image: "/image/poultry.jpg",
        description: "Large-scale poultry farming with modern techniques, automated systems, and market-driven approach.",

    },
    {
        id: 3,
        title: "Eid Panjabi Sales",
        category: "Retail",
        year: "2024",
        duration: "3 months",
        status: "Completed",
        profit: "Good",
        profitPercent: "30%",
        investment: "৳4L",
        returns: "৳4.3L",
        location: "Feni",
        members: 10,
        image: "/image/panjabi.avif",
        description:
            "Seasonal retail venture capitalizing on Eid festivities with premium clothing and traditional wear.",

    },
    {
        id: 4,
        title: "Cow Rearing for Eid-ul-Azha",
        category: "Livestock",
        year: "2024",
        duration: "4 months",
        status: "Completed",
        profit: "Good",
        profitPercent: "15%",
        investment: "৳5L",
        returns: "৳5.5L",
        location: "Feni",
        members: 12,
        image: "/image/cow.avif",
        description:
            "Strategic livestock investment for Eid-ul-Azha market with premium cattle and excellent profit margins.",
    },
    {
        id: 5,
        title: "Rice Trading Business",
        category: "Agriculture",
        year: "2024",
        duration: "12 months",
        status: "Ongoing",
        profit: "Good",
        profitPercent: "78%",
        investment: "৳5.0L",
        returns: "৳8.9L",
        location: "Feni",
        members: 9,
        image: "/image/Rice-Trading-Business.jpg",
        description: "Rice procurement and trading business connecting farmers with wholesale markets across Bangladesh.",
    },
    {
        id: 6,
        title: "Vegetable Farming",
        category: "Agriculture",
        year: "2023",
        duration: "10 months",
        status: "Completed",
        profit: "Good",
        profitPercent: "10%",
        investment: "৳1L",
        returns: "৳.2L",
        location: "Feni",
        members: 15,
        image: "/image/vasitable.webp",
        description: "Seasonal vegetable farming with focus on high-demand crops and direct market sales.",

    },
    {
        id: 7,
        title: "Grocery Store Chain",
        category: "Retail",
        year: "2024",
        duration: "1y",
        status: "Ongoing",
        profit: "Good",
        profitPercent: "45%",
        investment: "৳6.2L",
        returns: "৳9.0L",
        location: "Feni",
        members: 11,
        image: "/image/super_market.jpg",
        description: "Small grocery store chain serving local communities with essential goods and daily necessities.",

    },
    {
        id: 8,
        title: "Goat Farming Expansion",
        category: "Livestock",
        year: "2024",
        duration: "8 months",
        status: "Completed",
        profit: "Projected High",
        profitPercent: "75%",
        investment: "৳3.5L",
        returns: "৳6.1L",
        location: "Sylhet",
        members: 9,
        image: "/image/goat.jpg",
        description: "Expansion of goat farming operations with improved breeding techniques and market partnerships.",
        timeline: [
            { phase: "Farm Setup", status: "Completed", date: "Feb 2024" },
            { phase: "Livestock Acquisition", status: "Completed", date: "Mar 2024" },
            { phase: "Breeding Program", status: "In Progress", date: "Apr-Jul 2024" },
            { phase: "Market Sales", status: "Upcoming", date: "Aug 2024" },
        ],
        financials: {
            totalInvestment: "৳3.5L",
            currentSpent: "৳2.8L",
            expectedRevenue: "৳6.1L",
            projectedProfit: "৳2.6L",
            roi: "75%",
        },
    },
    {
        id: 9,
        title: "Seasonal Fruit Trading",
        category: "Retail",
        year: "2024",
        duration: "4 months",
        status: "Completed",
        profit: "Expected Excellent",
        profitPercent: "90%",
        investment: "৳1.5L",
        returns: "৳2.9L",
        location: "Dhaka",
        members: 5,
        image: "/image/fruits.jpg",
        description: "Strategic seasonal fruit trading focusing on premium quality fruits during peak demand periods.",
        timeline: [
            { phase: "Market Research", status: "Completed", date: "Mar 2024" },
            { phase: "Supplier Partnerships", status: "Completed", date: "Apr 2024" },
            { phase: "Active Trading", status: "In Progress", date: "May-Jun 2024" },
            { phase: "Season Completion", status: "Upcoming", date: "Jul 2024" },
        ],
        financials: {
            totalInvestment: "৳1.5L",
            currentSpent: "৳1.2L",
            expectedRevenue: "৳2.9L",
            projectedProfit: "৳1.4L",
            roi: "90%",
        },
    },
    {
        id: 10,
        title: "Organic Product Expansion Project",
        category: "Organic Farming & Products",
        year: "2024",
        duration: "18 months",
        status: "Ongoing",
        profit: "High & Sustainable",
        profitPercent: "95%",
        investment: "৳12.0L",
        returns: "৳23.4L",
        location: "Feni, Bangladesh",
        members: 9,
        image: "/image/projects/Vaizans-Organic.jpg",
        description:
            "Focused on expanding organic food production and distribution, including vegetables, fruits, and herbal items to promote healthy living and sustainable farming in Bangladesh.",
        timeline: [
            { phase: "Soil Preparation & Organic Certification", status: "Completed", date: "Mar 2024" },
            { phase: "Production & Cultivation", status: "Ongoing", date: "May 2024" },
            { phase: "Processing & Packaging", status: "Planned", date: "Dec 2024" },
            { phase: "Market Expansion & Export", status: "Planned", date: "Jun 2025" },
        ],
        financials: {
            totalInvestment: "৳12.0L",
            currentSpent: "৳5.5L",
            expectedRevenue: "৳23.4L",
            projectedProfit: "৳11.4L",
            roi: "95%",
        },
    },

    {
        id: 11,
        title: "Commercial Property Investment",
        category: "Property",
        year: "2024",
        duration: "24 months",
        status: "Planning",
        profit: "Long-term High",
        profitPercent: "120%",
        investment: "৳15.0L",
        returns: "৳33.0L",
        location: "Dhaka",
        members: 13,
        image: "/image/building.jfif",
        description:
            "Strategic commercial property investment in prime Dhaka location for rental income and appreciation.",
        timeline: [
            { phase: "Property Research", status: "In Progress", date: "Apr 2024" },
            { phase: "Due Diligence", status: "Planned", date: "Jun 2024" },
            { phase: "Acquisition", status: "Planned", date: "Aug 2024" },
            { phase: "Rental Operations", status: "Planned", date: "Sep 2024" },
        ],
        financials: {
            totalInvestment: "৳15.0L",
            currentSpent: "৳1.0L",
            expectedRevenue: "৳33.0L",
            projectedProfit: "৳18.0L",
            roi: "120%",
        },
    },
]

export const TEAM_GROUPS = [
    {
        group: "Group A",
        members: 10,
        status: "Senior Partners",
        description: "Experienced business leaders driving major investment decisions and strategic planning",
        experience: "4+ Years",
        totalInvestment: "৳10L+",
        successRate: "70%",
        specialties: ["Strategic Planning", "Risk Management", "Market Analysis", "Leadership"],
    },
    {
        group: "Group B",
        members: 5,
        status: "Growing Partners",
        description: "Dynamic new members bringing fresh perspectives, innovative ideas, and additional capital",
        experience: "3+ Years",
        totalInvestment: "৳5L+",
        successRate: "70%",
        specialties: ["Innovation", "Digital Marketing", "New Ventures", "Growth Strategy"],
    },
]


export const TEAM_MEMBER = [
    {
        id: 1,
        name: "Md. Rahman Ahmed",
        role: "Group A Lead & Founder",
        group: "Group A",
        expertise: ["Agriculture", "Livestock", "Strategic Planning", "Risk Management"],
        experience: "5+ Years",
        projects: 7,
        investment: "৳8L+",
        joinDate: "January 2022",
        bio: "Visionary leader and founder of Vaizans Group with extensive experience in agricultural ventures and business development. Led the group from inception to its current success with 70% profitable returns.",
        achievements: [
            "Founded Vaizans Group in 2021",
            "Led 7 successful projects with 70% success rate",
            "Pioneered sustainable farming practices",
            "Established strategic partnerships across Bangladesh",
        ],
        contact: {
            email: "rahman@vaizansgroup.com",
            phone: "+880 XXX-XXXXXXX",
            linkedin: "#",
        },
        image: "/image/teamProfile/profile3.jpg",
    },
    {
        id: 2,
        name: "Fatima Khan",
        role: "Retail & Trading Specialist",
        group: "Group A",
        expertise: ["Retail Management", "Market Analysis", "Supply Chain", "Customer Relations"],
        experience: "4+ Years",
        projects: 5,
        investment: "৳6L+",
        joinDate: "March 2022",
        bio: "Expert in retail operations and trading with a proven track record in seasonal business ventures. Spearheaded the highly successful Eid Panjabi sales project with 120% profit margins.",
        achievements: [
            "Led Eid Panjabi project with 120% returns",
            "Established retail network across 3 cities",
            "Developed customer acquisition strategies",
            "Managed supply chain optimization",
        ],
        contact: {
            email: "fatima@vaizansgroup.com",
            linkedin: "#",
        },
        image: "/image/teamProfile/profile2.jpg",
    },
    {
        id: 3,
        name: "Ahmed Ali Hassan",
        role: "Group B Lead & Digital Strategist",
        group: "Group B",
        expertise: ["Digital Marketing", "Business Development", "Technology", "Innovation"],
        experience: "3+ Years",
        projects: 4,
        investment: "৳4L+",
        joinDate: "June 2023",
        bio: "Dynamic leader of Group B bringing fresh perspectives and digital expertise to traditional business models. Focuses on leveraging technology for business growth and market expansion.",
        achievements: [
            "Established Group B expansion initiative",
            "Implemented digital marketing strategies",
            "Increased online presence by 300%",
            "Developed tech-driven business solutions",
        ],
        contact: {
            email: "ahmed@vaizansgroup.com",
            phone: "+880 XXX-XXXXXXX",
            linkedin: "#",
        },
        image: "/image/teamProfile/profile1.jpg",
    },
    {
        id: 4,
        name: "Nasir Uddin",
        role: "Finance & Investment Manager",
        group: "Group A",
        expertise: ["Financial Analysis", "Investment Planning", "Risk Assessment", "Portfolio Management"],
        experience: "6+ Years",
        projects: 7,
        investment: "৳7L+",
        joinDate: "February 2022",
        bio: "Seasoned financial expert responsible for investment analysis and portfolio management. Ensures all projects meet profitability targets and maintains the group's 70% success rate.",
        achievements: [
            "Managed ৳33L+ total investments",
            "Achieved 95% average profit margins",
            "Developed risk assessment frameworks",
            "Optimized investment allocation strategies",
        ],
        contact: {
            email: "nasir@vaizansgroup.com",
            linkedin: "#",
        },
        image: "/image/teamProfile/profile1.jpg",
    },
    {
        id: 5,
        name: "Rashida Begum",
        role: "Operations & Logistics Coordinator",
        group: "Group A",
        expertise: ["Operations Management", "Logistics", "Quality Control", "Team Coordination"],
        experience: "4+ Years",
        projects: 6,
        investment: "৳5L+",
        joinDate: "April 2022",
        bio: "Operations specialist ensuring smooth execution of all projects from planning to completion. Manages logistics, quality control, and team coordination across multiple ventures.",
        achievements: [
            "Streamlined operations across 6 projects",
            "Reduced operational costs by 15%",
            "Implemented quality control systems",
            "Coordinated multi-city project execution",
        ],
        contact: {
            email: "rashida@vaizansgroup.com",
        },
        image: "/image/teamProfile/profile3.jpg",
    },
    {
        id: 6,
        name: "Karim Abdullah",
        role: "Market Research Analyst",
        group: "Group A",
        expertise: ["Market Research", "Data Analysis", "Trend Forecasting", "Competitive Analysis"],
        experience: "3+ Years",
        projects: 5,
        investment: "৳4L+",
        joinDate: "May 2022",
        bio: "Data-driven analyst providing crucial market insights for investment decisions. Specializes in identifying profitable opportunities and market trends across various sectors.",
        achievements: [
            "Identified 12+ profitable opportunities",
            "Conducted market analysis for all sectors",
            "Developed forecasting models",
            "Provided strategic market insights",
        ],
        contact: {
            email: "karim@vaizansgroup.com",
        },
        image: "/image/teamProfile/profile2.jpg",
    },
    {
        id: 7,
        name: "Salma Khatun",
        role: "Community Relations Manager",
        group: "Group B",
        expertise: ["Community Engagement", "Public Relations", "Stakeholder Management", "Communication"],
        experience: "2+ Years",
        projects: 3,
        investment: "৳2L+",
        joinDate: "August 2023",
        bio: "Community engagement specialist building strong relationships with local stakeholders and communities. Ensures sustainable and socially responsible business practices.",
        achievements: [
            "Built partnerships with 20+ local communities",
            "Established CSR initiatives",
            "Improved community relations",
            "Developed stakeholder engagement programs",
        ],
        contact: {
            email: "salma@vaizansgroup.com",
        },
        image: "/image/teamProfile/profile1.jpg",
    },
    {
        id: 8,
        name: "Ibrahim Khan",
        role: "Technical Advisor",
        group: "Group B",
        expertise: ["Technical Consulting", "Innovation", "Process Optimization", "Quality Assurance"],
        experience: "4+ Years",
        projects: 4,
        investment: "৳3L+",
        joinDate: "September 2023",
        bio: "Technical expert providing innovative solutions and process optimization across all business ventures. Focuses on implementing modern techniques and quality assurance.",
        achievements: [
            "Implemented modern farming techniques",
            "Optimized production processes",
            "Introduced quality assurance systems",
            "Reduced technical risks by 25%",
        ],
        contact: {
            email: "ibrahim@vaizansgroup.com",
            linkedin: "#",
        },
        image: "/image/teamProfile/userProfile.png",
    },
]

export const SOCIAL_LINKS = [
    { name: "Facebook", icon: "Facebook", href: "#" },
    { name: "Twitter", icon: "Twitter", href: "#" },
    { name: "LinkedIn", icon: "Linkedin", href: "#" },
    { name: "WhatsApp", icon: "MessageSquare", href: "#" },
]

export const NEWS_DATA = [
    {
        id: 1,
        title: "Q4 2024 Investment Results: Record Breaking Returns",
        imageUrl: "/image/Rice-Trading-Business.jpg",
        excerpt:
            "Vaizans Group reports exceptional 95% average returns across all investment sectors with ambitious expansion plans for 2025.",
        date: "December 15, 2024",
        category: "Results",
        featured: true,
        readTime: "5 min read",
        author: "Group Leadership",
        tags: ["Results", "Investment", "Growth"],
    },
    {
        id: 2,
        title: "Strategic Land Acquisition in Prime Dhaka Location",
        imageUrl: "/image/vasitable.webp",
        excerpt:
            "Major property investment completed for upcoming residential development project worth ৳8.5L with projected 200% returns.",
        date: "December 10, 2024",
        category: "Investment",
        readTime: "3 min read",
        author: "Investment Team",
        tags: ["Property", "Land", "Development"],
    },
    {
        id: 3,
        title: "Group B Expansion: Welcoming New Strategic Partners",
        imageUrl: "/image/poultry.jpg",
        excerpt:
            "Successful onboarding of 2 new members to Group B, bringing total membership to 13+ with enhanced investment capacity.",
        date: "December 5, 2024",
        category: "Expansion",
        readTime: "4 min read",
        author: "HR Team",
        tags: ["Team", "Growth", "Partnership"],
    },
]

export const INVESTMENT_CATEGORIES = [
    {
        category: "Land & Property Development",
        icon: "Building",
        description: "Strategic land acquisitions in prime locations for future development and appreciation",
        currentValue: "৳15L+",
        status: "Active Acquisition",
        projects: 3,
        expectedReturn: "150-200%",
        timeframe: "2-3 years",
        color: "bg-green-100 text-green-800",
        locations: ["Dhaka", "Chittagong", "Sylhet"],
    },
    {
        category: "Residential Properties",
        icon: "Home",
        description: "Home investments for rental income generation and long-term capital appreciation",
        currentValue: "৳8L+",
        status: "Planning Phase",
        projects: 2,
        expectedReturn: "80-120%",
        timeframe: "3-5 years",
        color: "bg-blue-100 text-blue-800",
        locations: ["Dhaka", "Comilla"],
    },
    {
        category: "Commercial Spaces",
        icon: "ShoppingBag",
        description: "Shop and commercial property investments for business expansion and rental income",
        currentValue: "৳12L+",
        status: "Research Phase",
        projects: 4,
        expectedReturn: "100-180%",
        timeframe: "1-2 years",
        color: "bg-purple-100 text-purple-800",
        locations: ["Dhaka", "Chittagong", "Rangpur"],
    },
    {
        category: "New Business Ventures",
        icon: "TrendingUp",
        description: "Expansion into new profitable business sectors and scaling existing successful operations",
        currentValue: "৳10L+",
        status: "Ongoing Investment",
        projects: 5,
        expectedReturn: "60-150%",
        timeframe: "6 months - 2 years",
        color: "bg-yellow-100 text-yellow-800",
        locations: ["Multiple Cities"],
    },
]



